CREATE DATABASE IF NOT EXISTS DEMO;


CREATE SCHEMA IF NOT EXISTS PUBLIC;


-- Set the database and schema context
USE SCHEMA DEMO.PUBLIC;


-- Create the tables
CREATE OR REPLACE TABLE DEMO.PUBLIC.EY_DEMO_4
(
     TRIPDURATION INTEGER
    ,STARTTIME TIMESTAMP
    ,STOPTIME TIMESTAMP
    ,START_STATION_ID INTEGER
    ,START_STATION_NAME STRING
    ,GENDER INTEGER
    ,DESTINATION_STATION_ID INTEGER
    ,DESTINATION_STATION_NAME STRING
);

-- Create the tables
CREATEE OR REPLACE TABLE DEMO.PUBLIC.EY_DEMO_5
(
     TRIPDURATION INTEGER
    ,STARTTIME TIMESTAMP
    ,STOPTIME TIMESTAMP
    ,START_STATION_ID INTEGER
    ,START_STATION_NAME STRING
    ,GENDER INTEGER
    ,DESTINATION_STATION_ID INTEGER
    ,DESTINATION_STATION_NAME STRING
);

-- Create the tables
CREATE OR REPLACE TABLE DEMO.PUBLIC.EY_DEMO_6
(
     TRIPDURATION INTEGER
    ,STARTTIME TIMESTAMP
    ,STOPTIME TIMESTAMP
    ,START_STATION_ID INTEGER
    ,START_STATION_NAME STRING
    ,GENDER INTEGER
    ,DESTINATION_STATION_ID INTEGER
    ,DESTINATION_STATION_NAME STRING
);

